### ISSUE TITLE
Results incorrect at finite redshift and w!=-1

### ISSUE THREAD

**Issue by tijmen** [steven-murray/hmf#19]
The growth function used is not valid for wCDM. It is calculated by numerically integrating Equation 8 of Lukic+07. That equation is exactly 7.77 from Dodelson. Dodelson's textbook's errata page (http://home.fnal.gov/~dodelson/errata.html) points to a memo which provides the coupled PDEs to be solved. For Delta_w = 0.5, this causes a ~20% error in halo number density at z=0.6.

Possible solutions include correcting the growth function calculation, or obtaining the full P(k,z) from CAMB.

**Comment by steven-murray** [comment]
Thanks very much. Don't happen to have some time on your hands to write a routine to do this do you?

**Comment by tijmen** [comment]
I do not, sorry.

**Comment by steven-murray** [comment]
OK, fair enough.

I guess I will get to it eventually then!

**Comment by steven-murray** [comment]
I have worked on this in b639665fe207156bf6d852ed2f06c03a50da0814. 

My solution is to use the growth factor as determined by CAMB, rather than re-inventing the wheel. 

I would be very interested in your opinion on whether this works well enough.

The new growth factor model will be used by default if you are using wCDM cosmology and have pycamb installed. Otherwise, to use it, set ``growth_model="CambGrowth"`` when instantiating.

**Comment by tijmen** [comment]
Thanks for updating the implementation and posting about it. How accurate the redshift dependence of the halo mass function is under this method is an interesting science question, but this certainly seems like a very reasonable first order approach (it is the one that we used for the wCDM SPT cluster cosmology analysis).

**Comment by steven-murray** [comment]
Excellent. I will keep it as is, and if you have any other suggestions in the future, please let me know!
