### ISSUE TITLE
dlna is too large for functions of redshift

### ISSUE THREAD

**Issue by steven-murray** [steven-murray/hmf#31]
It seems that the default dlna=1e-2 (in growth factor) creates small-scale ripples in redshift-dependent(?) quantities, but using dlna=1e-4 eliminates them. Need to balance up what is the best default here, performance-wise, but add docs which explain this.

**Comment by mirochaj** [comment]
Yep -- just redshift-dependent quantities. No sign of any ill effects in Mh-dep quantities.

**Comment by thomasguillet** [comment]
Hi Steven,

It seems that the source of this issue is indeed in `GrowthFactor._d_plus()`, in particular at
```
lna = np.arange(np.log(self.params["amin"]), np.log(a_upper) + self.params['dlna'] / 2, self.params['dlna'])
```
Different values of `z` for which `np.log(a_upper)` differs by less than `self.params['dlna']` will produce a same `lna` array, and the change in upper integration bound will not be seen at all by the Simpson integration. This results in inaccuracies on the growth factor calculation, visible as quantization effects or ripples in z-dependent plots.

I see 2 easy solutions to this:

- Keep Simpson integration, but instead use sampling points like
```
lna = np.linspace(np.log(self.params["amin"]), np.log(a_upper), nlna)
```
where the number of points `nlna` is to be computed from the integration bounds and `self.params['dlna']`. This way, the samples for integration reach all the way up to `z` exactly without error (ie the last sampling point is always exactly `np.log(a_upper)`).

- Get rid of sample-based Simpson integration (at least for the case `getvec=False`) and use `scipy.integrate.quad` for general function-based integration on the range `np.log(self.params["amin"]), np.log(a_upper) `. FWIW, I believe `astropy.cosmology` uses `quad` extensively for this kind of integrals.

I see Simpson or `trapz` integration is used quite a bit throughout `hmf`; do you think there are other integrals that could be impacted by similar interval rounding issues?

Thanks and cheers!

**Comment by steven-murray** [comment]
Ahhh, good pickup!

I will update it to use linspace. I think I have used linspace rather than arange throughout for this very reason, but I will check other occurrences too. 

I think it makes more sense in these cases to use simps/trapz because the functions we have are by necessity discretized anyway. This is because the transfer function to begin with is numerical (at least if computed by CAMB). So function-based integration can't really be done. Also, simps/trapz integration is in my experience much faster. The only problem with it is that you have to know beforehand how many steps will be required to get the accuracy you want.

**Comment by steven-murray** [comment]
I've updated this in 4caa5e103a9fccc876758df72ac932c1ec83d356. Would be great if you could check it out and make sure it works! 

I had a look through the rest of the code -- there are a couple of uses of arange for integrals, but in each case the integral is not sensitive to the exact end-point, so all should be good.

Cheers,
Steven

**Comment by thomasguillet** [comment]
Hi Steven,

I've had a quick look at the growth factor in 4caa5e1 for z \in [0, 20] and compared against the previous `arange` code, testing against `quad` as a reference result. Using `linspace` is definitely a big improvement, and we go from relative errors of ~ 1.3% down to 0.06%.

I also compared the naive numerical derivatives of the growth factor for the 3 methods, to get a sense of how much we could trust comparisons at close redshifts. There's one thing that still nags me with `linspace`: while the computed growth factor itself now seems smooth, its numerical derivative is still visibly jaggy:

![dplus_diff](https://cloud.githubusercontent.com/assets/24361110/20881792/59de54b0-bade-11e6-8ff2-f58256bd3b9a.png)

This is a bit worrying for any study that depends finely on the redshift dependence of the HMF. I think this behavior is really inherent to tabulated integration methods. I agree 100% with you that tabulated integration is preferable for most integrals in `hmf`, and in particular the ones where you don't need to finely capture the behavior of the integral with respect to its bounds.

But considering the central role of the growth factor, and the remaining ripples when using `linspace`, maybe we should resort to `quad` for just this particular integral? That probably would not be very expensive overall.

What do you think?

Cheers,
Thomas

**Comment by thomasguillet** [comment]
Hmmm actually,`quad` is costlier than I thought:
```
import numpy as np
import hmf
mf = hmf.MassFunction()

def dplus(z):
    mf.update(z=z)
    return mf.growth_factor

%timeit [dplus(z) for z in np.linspace(0, 20, 1000)]
```
I get the following:
**linspace + simps:** `1 loop, best of 3: 1.26 s per loop`
**quad:** `1 loop, best of 3: 5.85 s per loop`

Assuming we don't want to pay the price of a full `quad`, maybe we can get away with this:
```
lna = np.arange(np.log(self.params["amin"]), np.log(a_upper), self.params['dlna'])
lna = np.hstack((lna, np.log(a_upper)))
```
and then integrate with
```
integral = intg.simps(np.exp(lna) * integrand, x=lna, even="first")
```
(mind the `x=lna`, instead of `dx=`, since the sampling points are now not regularly spaced anymore).

The advantage of this is that it preserves the nice property of arange than the sample points locations do not change with a_upper, but adds the small final interval of size < dlna which was missing from the initial arange implementation.

`even="first"` is meant to avoid potential oscillatory behavior in the integral when the number of points changes between even and odd from 2 close values of a_upper, but that's really being extra careful.

In practice, I did a quick test, and with the above `lna` and `simps`, it seems to be doing great compared to `quad`, even at the "jaggy derivative test".

**Comment by steven-murray** [comment]
Thanks so much for your detailed exploration. I was just having a play with it -- I noticed that my definition was inconsistent. I was integrating using dx = dlna, but dlna was slightly wrong because I was using an integer number of grid points. 

After fixing that, the jagged derivative is a lot better (still some extremely small glitches periodically, but they are really very small). I also tried your arange+hstack method, and it seems to do slightly better again, so I think I'll just use that.

Will push shortly.

**Comment by steven-murray** [comment]
Updated in 6b3337401404610b50924962294a0f7596e6c100. Looks much better to me. What do you think?

**Comment by thomasguillet** [comment]
Hi Steven,

6b33374 looks quite good to me! Regarding `even="avg"` vs `even="first"`: I think "avg" is in theory more accurate, while "first" has in principle the advantage that on N samples, the Simpson method will always evaluate the contribution of the N (or N-1 if N is even) first sample points in the same way, with maybe less of a risk of an even/odd oscillation when the right integral bound changes.

But in practice, I'm not sure that this really matters, and the overall accuracy of the integral seems quite good as it is now :)

Thanks a lot!

**Comment by steven-murray** [comment]
Thanks Thomas, 

Thanks for the explanation of the avg/first thing. In my couple of tests, it seemed that "first" was giving more bumps than "avg" (though both were very low amplitude), so that's why I chose to use it. More than willing to change it if it becomes a problem in a specific example!

I'll merge the changes into develop and close this issue -- feel free to re-open if problems re-emerge.

Cheers.
