### ISSUE TITLE
Error when using a transfer function from file-  __init__() got multiple values for keyword argument 'cosmo'

### ISSUE THREAD

**Issue by cwhite1026** [steven-murray/hmf#33]
I'm trying to make a MassFunction object with a transfer function from a file output by CAMB.  I had this working with an old version of HMF (not sure which- it's old enough it doesn't have `hmf.__version__` and pip is being uncooperative when I ask for information with pip show) but get an error with the new version.  The old code was 

```{python}
import hmf
options={}
options['fname']="/path/planck_for_hmf_transfer_out.dat"
mf=hmf.MassFunction(transfer_fit="FromFile", transfer_options=options, z=0)
```

The new code I'm using is

```{python}
import hmf 
options={}
options['fname']="planck_for_hmf_transfer_out.dat"
hmf_cosmo = hmf.cosmo.get_cosmo("Planck15")
mf = hmf.MassFunction(z=0, transfer_model = hmf.transfer_models.FromFile, 
                      transfer_params={'cosmo': hmf_cosmo, 'model_parameters':options})
```

This executes without a problem and I can grab `delta_c = mf.delta_c`, but when I ask for `mf.radii`, I get an error that is essentially complaining that I'm trying to give it the cosmology twice.  I've attached the error message (from iPython) as with_cosmo.txt.

If I run instead
```{python}
mf = hmf.MassFunction(z=0, transfer_model = hmf.transfer_models.FromFile, 
                      transfer_params={'model_parameters':options})
```
it also doesn't work but gives a different error.  I've attached this error message as without_cosmo.txt.  Passing `cosmo` as a keyword argument to `MassFunction()` doesn't work because it doesn't expect `cosmo` as an argument.  I've attached my CAMB output file as well (I had to change the file from .dat to .txt for github to take it, but it's plain text either way so I think it should be ok).

I'm not sure if this is really a bug or if I'm just doing it wrong- I couldn't find much of anything in the documentation about how to deal with reading a transfer function from a file.  Any help is appreciated.  In case you need to know about dependencies, I've attached the info on the conda environment I'm running the new code in.

[with_cosmo.txt](https://github.com/steven-murray/hmf/files/428073/with_cosmo.txt)
[without_cosmo.txt](https://github.com/steven-murray/hmf/files/428072/without_cosmo.txt)
[planck_for_hmf_transfer_out.txt](https://github.com/steven-murray/hmf/files/428074/planck_for_hmf_transfer_out.txt)
[conda_environment_updated_hmf.txt](https://github.com/steven-murray/hmf/files/428077/conda_environment_updated_hmf.txt)

**Comment by steven-murray** [comment]
Hi Catherine, thanks for the detailed report. 

On first glance, I suspect the problem is that "cosmo" has been renamed to "cosmo_params" , and is not passed to the transfer_params. To do what you are trying to do, I would use the following:

```python
import hmf 
options={}
options['fname']="planck_for_hmf_transfer_out.dat"
mf = hmf.MassFunction(z=0, transfer_model = "FromFile", 
                                                   transfer_params=options,
                                                   cosmo_model="Planck15")
```

From version 2+, all components have two inputs -- a ``<component>_model`` and ``<component>_params``. The first is either a string (such as ``"FromFile"``) *or* a class (such as what you were using: ``hmf.transfer_models.FromFile``), and defines the overall model. The second is a dictionary within which are any particular parameters for that component model (so in this case, the dictionary should just be ``{"fname":"the_file_name.txt"}``).

The cosmology is no different -- the "model" here sets the basic model with parameters (actually, there is a slight difference with cosmology, because you can either pass a string or an *instantiated* object, but that's kind of hidden from the user). The "params" argument is again a dictionary with the keys being cosmological parameter names, and their values. These over-write the base parameters invoked in the model itself. Do note that sigma_8 and the spectral index (still called ``n``) are *not* part of the cosmology, and are passed as parameters directly to ``MassFunction``. 

I hope that helps, and let me know if you have any more problems!

I also note your point about the documentation being insufficient, and I hope to rectify that as soon as I can.

**Comment by cwhite1026** [comment]
Awesome, that fixed it.  Sorry for raising an issue for user error!

PS- The documentation comment was intended more as an “I promise I tried to fix it myself” than “The documentation is lacking.”  I’m working on getting some code ready for release and documentation is miserable and takes forever.

On Aug 21, 2016, at 10:13 PM, Steven Murray <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Catherine, thanks for the detailed report.

On first glance, I suspect the problem is that "cosmo" has been renamed to "cosmo_params" , and is not passed to the transfer_params. To do what you are trying to do, I would use the following:

import hmf
options={}
options['fname']="planck_for_hmf_transfer_out.dat"
mf = hmf.MassFunction(z=0, transfer_model = "FromFile",
                                                   transfer_params=options,
                                                   cosmo_model="Planck15")

From version 2+, all components have two inputs -- a <component>_model and <component>_params. The first is either a string (such as "FromFile") or a class (such as what you were using: hmf.transfer_models.FromFile), and defines the overall model. The second is a dictionary within which are any particular parameters for that component model (so in this case, the dictionary should just be {"fname":"the_file_name.txt"}).

The cosmology is no different -- the "model" here sets the basic model with parameters (actually, there is a slight difference with cosmology, because you can either pass a string or an instantiated object, but that's kind of hidden from the user). The "params" argument is again a dictionary with the keys being cosmological parameter names, and their values. These over-write the base parameters invoked in the model itself. Do note that sigma_8 and the spectral index (still called n) are not part of the cosmology, and are passed as parameters directly to MassFunction.

I hope that helps, and let me know if you have any more problems!

I also note your point about the documentation being insufficient, and I hope to rectify that as soon as I can.

**Comment by steven-murray** [comment]
Thanks for that. Hope all goes well with the release!
