### ISSUE TITLE
No handlers could be found for logger "hmf"

### ISSUE THREAD

**Issue by StephenJTurnbull** [steven-murray/hmf#4]
Goodmorning Steven, 

I was wondering if you had encountered an error: 

---

cumulative_mass_func = hmf.ngtm
No handlers could be found for logger "hmf"

---

before? 

I was following your sample code from "http://hmf.readthedocs.org/en/latest/index.html"
In [1]: from hmf import MassFunction
In [2]: hmf = MassFunction()
In [3]: mass_func = hmf.dndlnm
In [4]: mass_variance = hmf.sigma
In [5]: cumulative_mass_func = hmf.ngtm
and it returned that error. 

Thank you for any time you can spare to assist.

I have a readout of the install, but the install readout is too long for this submission : "There was an error creating your Issue: body is too long. "

Stephen Turnbull

**Comment by steven-murray** [comment]
HI Stephen,

It's a bit odd that you got an error on the simple example! The particular error that you got is because you haven't set up a logger to report the true error. I do need to fix this behaviour (it is very unintuitive and clunky) at some point (hopefully soon, but I have a Thesis to complete!). In any case, you can see the actual error by setting up a logger like this:

```python
    import logging
    hmflog = logging.getLogger("hmf")
    hmflog.addHandler(logging.StreamHandler())
```
That is something you shouldn't have to do yourself, but as I said, I need to fix it at some point. In any case, that should print to screen the actual error that is occurring, which we can then try to fix. My bet is that the error says that you don't have CAMB installed ;)

**Comment by StephenJTurnbull** [comment]
When I installed CAMB it didn't complain. 
and
import pycamb 
Works as advertised . . . I think.

import sys
import logging
from hmf import MassFunction

ch = logging.StreamHandler(sys.stdout)
hmflog = logging.getLogger("hmf")
hmflog.addHandler(logging.StreamHandler())
mass_func = hmf.dndlnmfrom hmf import MassFunction
hmf = MassFunction()
mass_func = hmf.dndlnm
mass_variance = hmf.sigma
hmf.update(omegab = 0.05,z=10)
cumulative_mass_func = hmf.ngtm
The specified mass-range was almost entirely                             outside of the limits from the fit. Ignored fit range...
The specified mass-range was almost entirely                             outside of the limits from the fit. Ignored fit range...

**Comment by steven-murray** [comment]
Hi Stephen,
Okay, the error there is coming up because the mass range specified is mostly (I think  >80%) outside the range of the fit that you're using (I think the default fit is Tinker08, but you can check which it's using by `hmf.mf_fit`). 

In general, there's two ways of getting rid of this warning -- either change the mass range, or when instantiating, use  `hmf = MassFunction(cut_fit=False)`. However, the latter should give you exactly the same result that you have now (just without the warning).

The odd thing is, this warning shouldn't be coming up for the default example. The default mass range is 10^10 - 10^15 h^-1 M_sun, which is precisely the Tinker08 mass range. So you can check those values (check `hmf.Mmin` and `hmf.Mmax`). 

Cheers,
Steven

**Comment by StephenJTurnbull** [comment]
As you said, the mass ranges are correct. 

hmf.mf_fit
Out[8]: hmf.fitting_functions.Tinker08
In [7]: hmf.Mmin
Out[7]: 10
In [6]: hmf.Mmax
Out[6]: 15In [8]: 

Should I simply ignore the warning?

**Comment by steven-murray** [comment]
Hi Stephen,

I was wrong about the exact mass cuts for Tinker08 -- I just had a look at the code and it says:

```python
        if cut_fit:
            if self.z == 0.0:
                vfv[np.logical_or(self.lnsigma / np.log(10) < -0.6 ,
                                  self.lnsigma / np.log(10) > 0.4)] = np.nan
            else:
                vfv[np.logical_or(self.lnsigma / np.log(10) < -0.2 ,
                                  self.lnsigma / np.log(10) > 0.4)] = np.nan
```
So if you're using the default redshift 0, then the function should be cut at log_10(1/sigma) = -0.6 and 0.4. You can check the values you're generating for this quantity by

```
hmf.lnsigma.min()/np.log(10)
hmf.lnsigma.max()/np.log(10)
```
For your mass range, most of the masses should be inside this range. For instance, I just ran it now and got
```
In [6]: hmf.lnsigma.min()/log(10)
Out[6]: -0.58428901837496061

In [7]: hmf.lnsigma.max()/log(10)
Out[7]: 0.28098077288873397
```
If these values are wildly different, then something weird is going on.

**Comment by StephenJTurnbull** [comment]
In [18]: h.lnsigma.min()/math.log(10)
Out[18]: -0.58725447038011647

In [19]: h.lnsigma.max()/math.log(10)
Out[19]: 0.25693207174218674

Mine and yours agree to within the stochastic expectations. 
Why is mine giving me a warning on runtime then?

**Comment by steven-murray** [comment]
Hmmm very strange. If I were in this situation now, I would do the following (which you can temporarily as well if you can edit the source code of hmf). Replace the `fsigma` method of Tinker08 (situated at about line 490 of the fitting_functions.py module) with

```python

    def fsigma(self, cut_fit):
        vfv = self.A * ((self.sigma / self.b) ** (-self.a) + 1) * np.exp(-self.c / self.sigma ** 2)
        print "NANS IN ORIGINAL VFV: ", np.sum(np.isnan(vfv))

        if cut_fit:
            if self.z == 0.0:
                vfv[np.logical_or(self.lnsigma / np.log(10) < -0.6 ,
                                  self.lnsigma / np.log(10) > 0.4)] = np.nan
                print "NANS IN CUT VFV: ", np.sum(np.isnan(vfv)), vfv[0], vfv[-1]
                print "MIN/MAX LNSIGMA: ", self.lnsigma.min()/np.log(10),self.lnsigma.max()/np.log(10)
            else:
                vfv[np.logical_or(self.lnsigma / np.log(10) < -0.2 ,
                                  self.lnsigma / np.log(10) > 0.4)] = np.nan
        return vfv
```

This should tell you where the NaN's are coming from. Basically, this result is passed back to the `fsigma` method of the main `MassFunction` class, which checks what percentage of NaN's there are in the array. If most are NaN's, it (probably unreasonably, this is fixed in the development branch at the moment) issues your warning, and forces cut_fit to be False, and redoes the calculation.

Sorry about all the hassle -- I do hope it's worth sorting out!

**Comment by steven-murray** [comment]
Hi did this ever get sorted out?

**Comment by StephenJTurnbull** [comment]
Yes, sorry, adding the 'include logger' got it working. 

Thank you again.

Date: Wed, 19 Aug 2015 21:12:45 -0700

**Comment by steven-murray** [comment]
Thank you!
