### ISSUE TITLE
NaNs with Bhattacharya mass function

### ISSUE THREAD

**Issue by abensonca** [steven-murray/hmf#44]
The Bhattacharya mass function at z=0 with default cosmological parameters produces NaNs in the output via the HMFcalc interface, even with "Restrict mass range to fitted range?" checked. Here's the corresponding parameters.txt:

```
File Created On: 2019-08-09 00:12:09.914416
With version 1.0.5 of HMFcalc 
And version 1.7.0 of hmf (backend) 

SETS OF PARAMETERS USED 
=====================================================
   PLANCK-SMT 
=====================================================
Mmax: 15.0 
tau: 0.0925 
Mmin: 10.0 
transfer_options: {'fname': u'transfers/PLANCK_transfer.dat'} 
cs2_lam: 1 
cut_fit: True 
t_cmb: 2.725 
dlog10m: 0.05 
omegam: 0.2715 
N_nu: 3.04 
omegan: 0.0 
transfer_fit: FromFile 
omegak: 0.0005 
omegac: 0.226 
omegab: 0.0455 
nz: None 
z_reion: 11.35 
N_nu_massive: 0.0 
omegav: 0.728 
_fsig_params: {} 
delta_wrt: mean 
lnk_min: -15.0 
delta_h: 200.0 
wdm_mass: None 
z2: None 
delta_c: 1.686 
sigma_8: 0.81 
dlnk: 0.05 
h: 0.704 
H0: 70.4 
lnk_max: 15.0 
n: 0.967 
w: -1 
z: 0.0 
y_he: 0.24 
mf_fit: Bhattacharya 
```

The mass function is NaN up to about 6.0e11Msun/h. Above that the values are no longer NaN, but also don't agree with my own implementation of the Bhattacharya mass function (I'm not saying my implementation is correct - I was actually trying to validate it against HMFcalc when I found this problem).

**Comment by steven-murray** [comment]
Thanks for letting me know!

To address the first problem (with NaNs): when the option "Restrict mass range to fitted range?" is _checked_, it will generate NaNs outside the range that the original function was fit to (this behaviour is modified in the most recent version of the hmf library -- this version is scheduled to be uploaded to the web-app soon). So that makes sense (it should remove the NaNs if this is unchecked. If not, please let me know!).

I would be interested in determining the sources of difference between HMFcalc and your own implementation of Bhattacharya. Do you have a plot comparing the two for default parameters? I can also try running with the latest version of `hmf` to see if there are any changes.

**Comment by abensonca** [comment]
Thanks for the explanation about the NaN values - unchecking the "Restrict mass range to fitted range?" does solve that problem.

Here's a plot showing the difference. Red lines are the Sheth Tormen mass function, blue lines are Bhattacharya. Dashed are from HMFcalc and dotted are from my code.

![Spectacle ZKP689](https://user-images.githubusercontent.com/7468651/63054576-fcf91700-be98-11e9-9640-4bdcbd02d42c.png)

The Sheth-Tormen results agree very closely between HMFcalc and my code - so I'm sure that I'm correctly matching the cosmological parameters, power spectrum, sigma(M) calculation etc.

The Bhattacharya from HMFcalc looks very different which makes me suspect there's a problem. But, looking through the hmf code I don't see anything that differs from what I'm doing...... So, I'm confused!

**Comment by steven-murray** [comment]
Oh wow that is strange.

Here's a plot comparing SMT (blue) to Bhattacharya (orange) for the latest version of hmf, with default parameters (these may not be the same as the defaults on HMFcalc). 

![Figure_1](https://user-images.githubusercontent.com/1272030/63056662-5f541680-be9d-11e9-884d-952c41406a5d.png)

The match is much more close. Perhaps there was a bug in the version that HMFcalc is using which has since been fixed. I should be able to check the git logs for it if you're particularly concerned!

**Comment by abensonca** [comment]
Thanks - that looks much closer to what I get. I'll just skip this comparison in my tests for now. if HMFcalc is going to be updated soon then I'll reinstate the test after that, or I can always install hmf and compute it using the updated code. Thanks!

**Comment by steven-murray** [comment]
Located the fix: 0c2ec1a (v2.0.4).

**Comment by steven-murray** [comment]
I will try to remember to let you know when the new code is up on HMFcalc -- it's been a bit of a struggle as I'm not at the hosting institution any more.

**Comment by abensonca** [comment]
Thanks!

**Comment by steven-murray** [comment]
@abensonca this is fixed in the new web-app at https://thehalomod.app. Thanks!

**Comment by abensonca** [comment]
Thanks!
